### ISSUE TITLE
mtj-softtuner fails to install + jaxlib requirements not met

### ISSUE THREAD

**Issue by Sherwood321** [VE-FORBRYDERNE/mtj-softtuner#19]
Hi.

So I ran the Google Colab and from the first stage I get the jaxlib requirement error and a module error stating mjt-softtuner not installed.

Adding the output below:

Cloning into 'mtj-softtuner'...
remote: Enumerating objects: 831, done.
remote: Counting objects: 100% (323/323), done.
remote: Compressing objects: 100% (123/123), done.
remote: Total 831 (delta 218), reused 267 (delta 192), pack-reused 508
Receiving objects: 100% (831/831), 419.32 KiB | 2.85 MiB/s, done.
Resolving deltas: 100% (501/501), done.
Submodule 'mtj_softtuner/kobold' (https://github.com/henk717/KoboldAI-Client) registered for path 'mtj_softtuner/kobold'
Cloning into '/content/mtj-softtuner/mtj_softtuner/kobold'...
Submodule path 'mtj_softtuner/kobold': checked out '61511a57144689da007fc049f88d5a858d99ab19'
Submodule 'KoboldAI-Horde-Bridge' (https://github.com/db0/KoboldAI-Horde-Bridge) registered for path 'mtj_softtuner/kobold/KoboldAI-Horde-Bridge'
Cloning into '/content/mtj-softtuner/mtj_softtuner/kobold/KoboldAI-Horde-Bridge'...
Submodule path 'mtj_softtuner/kobold/KoboldAI-Horde-Bridge': checked out 'd9014ebac969c0e5c37eb5456deebc3518130391'
WARNING: Skipping mtj-softtuner as it is not installed.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing /content/mtj-softtuner
  Preparing metadata (setup.py) ... done
Collecting mesh_transformer@ git+https://github.com/VE-FORBRYDERNE/mesh-transformer-jax#egg=mesh_transformer
  Cloning https://github.com/VE-FORBRYDERNE/mesh-transformer-jax to /tmp/pip-install-6o8j4eq4/mesh-transformer_b900c0fde8074c29b6f1f66dab7288b0
  Running command git clone --filter=blob:none --quiet https://github.com/VE-FORBRYDERNE/mesh-transformer-jax /tmp/pip-install-6o8j4eq4/mesh-transformer_b900c0fde8074c29b6f1f66dab7288b0
  Resolved https://github.com/VE-FORBRYDERNE/mesh-transformer-jax to commit 3febb8e003c18553266b6c2fdcfa60d1647fbc1c
  Preparing metadata (setup.py) ... done
Collecting torch<=1.11,>=1.9
  Downloading torch-1.11.0-cp310-cp310-manylinux1_x86_64.whl (750.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 750.6/750.6 MB 2.0 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from mtj-softtuner==1.3.6) (1.24.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from mtj-softtuner==1.3.6) (4.65.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from mtj-softtuner==1.3.6) (2.27.1)
Collecting optax<=0.1.2,>=0.1.0
  Downloading optax-0.1.2-py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.7/140.7 kB 15.9 MB/s eta 0:00:00
Collecting dm-haiku==0.0.5
  Downloading dm_haiku-0.0.5-py3-none-any.whl (287 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.3/287.3 kB 22.5 MB/s eta 0:00:00
Collecting chex<0.1.3,>=0.0.7
  Downloading chex-0.1.2-py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.3/72.3 kB 8.4 MB/s eta 0:00:00
Collecting jax==0.2.12
  Downloading jax-0.2.12.tar.gz (590 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.8/590.8 kB 49.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
**ERROR: Could not find a version that satisfies the requirement jaxlib==0.1.68 (from mtj-softtuner) (from versions: 0.1.75, 0.1.76, 0.3.0, 0.3.2, 0.3.5, 0.3.7, 0.3.10, 0.3.14, 0.3.15, 0.3.20, 0.3.22, 0.3.24, 0.3.25, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7)
ERROR: No matching distribution found for jaxlib==0.1.68

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-1-b3f60fda0965>](https://localhost:8080/#) in <cell line: 6>()
      4 get_ipython().system('bash mtj-softtuner/install.sh')
      5 
----> 6 import mtj_softtuner
      7 
      8 import os

ModuleNotFoundError: No module named 'mtj_softtuner'**

**Comment by shinkarom** [comment]
Second this.

**Comment by rondlite** [comment]
The collab runs python 3.10 by now but the repo only works on 3.9 due to the jaxlib not being on 3.10 for that version.. trying if i can fix it

**Comment by Sherwood321** [comment]
Ah brilliant. Thanks for the clarification and good luck with the resolution.

**Comment by Sherwood321** [comment]
@rondlite - Hey bud. Any joy with the fix? What would the fix entail out of curiousity.

**Comment by rondlite** [comment]
> @rondlite - Hey bud. Any joy with the fix? What would the fix entail out of curiousity.

I got it working in a conda environment forcing the python to 3.9 with `conda install python==3.9`

**Comment by Sherwood321** [comment]
No longer pursuing Soft Tuning. Lora seems to be the way to go.
